#!/usr/bin/env ruby
# encoding: utf-8

puts "Deploying environment..."

dir = Dir.pwd

bash_subfiles = %w[
  bash/functions.sh
  bash/path.sh
  bash/prompt.sh
  bash/settings.sh
]

dotfiles = %w[
  bash/profile
  dotfiles/aprc
  dotfiles/gemrc
  dotfiles/gitconfig
  dotfiles/gitignore
  dotfiles/hushlogin
  dotfiles/irbrc
  dotfiles/inputrc
  dotfiles/ruby-version
  dotfiles/tm_properties
]

binfiles = %w[
  random
  lb-spec
  hbucket-sync
]

system "mkdir -pv ~/.bash"
system "mkdir -pv /usr/local/bin"

bash_subfiles.each do |file|
  system "cp -fv #{dir}/#{file} ~/.#{file}"
  system "chmod -vv 750 ~/.#{file}"
end

dotfiles.each do |file|
  target_name = file.split("/").last
  system "cp -fv #{dir}/#{file} ~/.#{target_name}"
  system "chmod -vv 750 ~/.#{target_name}"
end

binfiles.each do |file|
  system "cp -fv #{dir}/bin/#{file} /usr/local/bin/#{file}"
  system "chmod -vv 755 /usr/local/bin/#{file}"
end

puts "Environment deployed ✔"
