#!/usr/bin/env ruby
# encoding: utf-8

puts "Deploying environment..."

@dir = Dir.pwd

@bash_files = Dir.glob("#{@dir}/bash/*")
@dotfiles   = Dir.glob("#{@dir}/dotfiles/*")
@binfiles   = Dir.glob("#{@dir}/bin/*")

system "mkdir -pv ~/.bash"
system "mkdir -pv /usr/local/bin"

@bash_files.each do |file|
  system "cp -fv #{file} ~/.bash/#{File.basename(file)}"
  system "chmod -vv 750 ~/.bash/#{File.basename(file)}"
end

@dotfiles.each do |file|
  target_name = file.split("/").last
  system "cp -fv #{file} ~/.#{File.basename(file)}"
  system "chmod -vv 750 ~/.#{File.basename(file)}"
end

@binfiles.each do |file|
  system "cp -fv #{file} /usr/local/bin/#{File.basename(file)}"
  system "chmod -vv 755 /usr/local/bin/#{File.basename(file)}"
end

system "cp -fv #{@dir}/library/com.apple.DownloadAssessment.plist ~/Library/Preferences/com.apple.DownloadAssessment.plist"

puts "Environment deployed ✔"
