#!/usr/bin/env ruby

puts "Installing favorite tools..."

fav_packages = %w[
  awscli
  heroku
  chruby
  ffmpeg
  git
  node
  imagemagick
  jpeg
  openssl
  pngcrush
  ruby-install
  ssh-copy-id
  tree
  wget
  youtube-dl
]

system "brew update"
system "brew install #{fav_packages.join(" ")}"

# Install Ruby dependencies
system "brew install readline gdbm libyaml jemalloc"

# Just check one more time...
system "brew upgrade"
system "brew cleanup"
system "brew prune"

puts "Tools installed ✔"
puts "Setting up Heroku"

system "heroku login"
system "heroku plugins:install heroku-repo"
system "heroku plugins:install heroku-pg-extras"
